<a href="https://colab.research.google.com/github/Chandsi-06/NNDL_Practicals/blob/main/NNDL_prac1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
vector1 = np.array([10, 20, 30])
vector2 = np.array([5, 10, 15])
print("Vector 1 =", vector1)
print("Vector 2 =", vector2)
result = vector1 + vector2
print("Vector Addition =", result)
import numpy as np
A = np.array([[1, 2],
 [3, 4]])
B = np.array([[5, 6],
 [7, 8]])
print("Matrix A")
print(A)
print()
print("Matrix B")
print(B)
C = np.matmul(A, B)
print("Matrix Multiplication")
print(C)

Vector 1 = [10 20 30]
Vector 2 = [ 5 10 15]
Vector Addition = [15 30 45]
Matrix A
[[1 2]
 [3 4]]

Matrix B
[[5 6]
 [7 8]]
Matrix Multiplication
[[19 22]
 [43 50]]
